export const categories = [
  { id: "combo", name: "Combo" },
  { id: "special", name: "Special" },
  { id: "breakfast", name: "Breakfast" },
  { id: "bread-items", name: "Bread Items" },
  { id: "beef-items", name: "Beef Items" },
  { id: "chicken", name: "Chicken" },
  { id: "charcoal", name: "Charcoal" },
  { id: "curry", name: "Curry" },
  { id: "north-indian", name: "North Indian" },
  { id: "veg-rice", name: "Veg & Rice" },
  { id: "chinese", name: "Chinese" },
  { id: "burger", name: "Burger" },
  { id: "sandwich", name: "Sandwich" },
  { id: "egg-items", name: "Egg Items" },
  { id: "fish-items", name: "Fish Items" },
  { id: "lunch", name: "Lunch" },
  { id: "soup", name: "Soup" },
  { id: "fresh-juices", name: "Fresh Juices" },
  { id: "mix-juice", name: "Mix Juice" },
  { id: "soft-drinks", name: "Soft Drinks" },
];

export const menuData = {
  "combo": [
    // COMBO
    { name: "Chi. Noodles + Chi. Manchurian / Chi. Chilli", price: "AED 15.00", section: "Combo" },
    { name: "Fried Rice + Chicken Chilli", price: "AED 20.50", section: "Combo" },
    { name: "Fried Rice + Chicken Manchurian", price: "AED 17.50", section: "Combo" },
    { name: "Chi. Kurma + Poratta", price: "AED 11.00", section: "Combo" },
    { name: "Chicken Curry + Chappathi / Poratta", price: "AED 8.00", section: "Combo" },
    { name: "Chicken Fry + Chappathi / Poratta / Dosa", price: "AED 10.00", section: "Combo" },
    { name: "Chicken Roast + Chappathi / Poratta / Dosa", price: "AED 10.00", section: "Combo" },
    { name: "Combo Ghee Rice + Chicken Fry", price: "AED 12.00", section: "Combo" },
    { name: "Egg Roast + Paratha", price: "AED 6.00", section: "Combo" },
    { name: "Ghee Rice + Chicken / Beef / Fish Curry", price: "AED 10 / 12 / 12", section: "Combo" },
    { name: "Puttum Beefum", price: "AED 16.00", section: "Combo" },
    { name: "Veg Kurma + Chappathi / Dosa / Poratta", price: "AED 6.00", section: "Combo" },
  ],
  "special": [
    // SPECIAL
    { name: "Erachi Chor Beef", price: "AED 12.00", section: "Special" },
    { name: "Erachi Chor Chicken", price: "AED 10.00", section: "Special" },
    { name: "Ayala Mulakittathu", price: "AED 8.00", section: "Special" },
    { name: "Chicken Chukka", price: "AED 10.00", section: "Special" },
    { name: "Chicken Kondattam", price: "AED 16.00", section: "Special" },
    { name: "Chicken Mandi", price: "AED 12.00", section: "Special" },
    { name: "Chicken Stew", price: "AED 10.00", section: "Special" },
    { name: "Fish Mulakittathu", price: "AED 8.00", section: "Special" },
    { name: "Fish Pollichathu", price: "AED 15.00", section: "Special" },
    { name: "Fish Tawa Fry", price: "AED 15.00", section: "Special" },
    { name: "Kanji Set", price: "AED 8.00", section: "Special" },
    { name: "Kappa", price: "AED 5.00", section: "Special" },
    { name: "Kappa Biriyani", price: "AED 12.00", section: "Special" },
    { name: "Kapparotti Chicken", price: "AED 15.00", section: "Special" },
    { name: "Kizhi Poratta Beef", price: "AED 15.00", section: "Special" },
    { name: "Kizhi Poratta Chicken", price: "AED 12.00", section: "Special" },
    { name: "Kothu Paratha Beef", price: "AED 12.00", section: "Special" },
    { name: "Kothu Poratta", price: "AED 10.00", section: "Special" },
    { name: "Majboos", price: "AED 10.00", section: "Special" },
    { name: "Kappayum + Beefum", price: "AED 12.00", section: "Special" },
  ],
  "breakfast": [
    // BREAKFAST
    { name: "Appam", price: "AED 1.25", section: "Breakfast" },
    { name: "Appam Egg Curry", price: "AED 5.00", section: "Breakfast" },
    { name: "Appam Egg Roast", price: "AED 6.00", section: "Breakfast" },
    { name: "Baji", price: "AED 3.00", section: "Breakfast" },
    { name: "Dosa", price: "AED 1.00", section: "Breakfast" },
    { name: "Dosa Set (2 Pcs)", price: "AED 3.00", section: "Breakfast" },
    { name: "Egg Curry", price: "AED 3.00", section: "Breakfast" },
    { name: "Egg Dosa", price: "AED 6.00", section: "Breakfast" },
    { name: "Egg Roast Breakfast", price: "AED 3.00", section: "Breakfast" },
    { name: "Ghee Dosa", price: "AED 5.00", section: "Breakfast" },
    { name: "Green Pease Curry", price: "AED 3.00", section: "Breakfast" },
    { name: "Idiyappam", price: "AED 1.00", section: "Breakfast" },
    { name: "Idly Set (2 Pcs)", price: "AED 3.00", section: "Breakfast" },
    { name: "Kadala Curry", price: "AED 3.00", section: "Breakfast" },
    { name: "Masala Dosa", price: "AED 5.00", section: "Breakfast" },
    { name: "Nadan Chicken Curry", price: "AED 5.00", section: "Breakfast" },
    { name: "Onion Uthappam", price: "AED 6.00", section: "Breakfast" },
    { name: "Plain Dosa", price: "AED 4.00", section: "Breakfast" },
    { name: "Poratta Chicken Curry", price: "AED 7.00", section: "Breakfast" },
    { name: "Poratta Egg Roast", price: "AED 5.00", section: "Breakfast" },
    { name: "Puri", price: "AED 1.00", section: "Breakfast" },
    { name: "Puri Bhaji", price: "AED 4.00", section: "Breakfast" },
    { name: "Puttu", price: "AED 3.00", section: "Breakfast" },
    { name: "Puttu Green Pease Curry", price: "AED 5.00", section: "Breakfast" },
    { name: "Puttu Kadala Curry", price: "AED 5.00", section: "Breakfast" },
    { name: "Puttum Cherupayarum", price: "AED 5.00", section: "Breakfast" },
    { name: "Upmav", price: "AED 3.00", section: "Breakfast" },
    { name: "Vada Set (2 Pcs)", price: "AED 4.00", section: "Breakfast" },
    { name: "Veg Kurma Breakfast", price: "AED 3.00", section: "Breakfast" },
    { name: "Vellappam", price: "AED 1.50", section: "Breakfast" },
    { name: "Idly Single", price: "AED 1.00", section: "Breakfast" },
    { name: "Dosa Single", price: "AED 1.00", section: "Breakfast" },
  ],
  "bread-items": [
    // BREAD ITEMS
    { name: "Butter Chappathi", price: "AED 1.50", section: "Breads" },
    { name: "Chappathi", price: "AED 1.00", section: "Breads" },
    { name: "Poratta", price: "AED 1.00", section: "Breads" },
  ],
  "beef-items": [
    // BEEF ITEMS
    { name: "Beef Curry", price: "AED 8.00", section: "Beef" },
    { name: "Beef Fry", price: "AED 12.00", section: "Beef" },
    { name: "Beef Fry Large", price: "AED 15.00", section: "Beef" },
    { name: "Beef Roast", price: "AED 12.00", section: "Beef" },
  ],
  "chicken": [
    // CHICKEN
    { name: "Butter Chicken", price: "AED 16.00", section: "Chicken" },
    { name: "Chicken Curry", price: "AED 10.00", section: "Chicken" },
    { name: "Chicken Fry", price: "AED 10.00", section: "Chicken" },
    { name: "Chicken Roast", price: "AED 10.00", section: "Chicken" },
    { name: "Chicken Roast Full", price: "AED 15.00", section: "Chicken" },
    { name: "Nadan Chicken Curry", price: "AED 5.00", section: "Chicken" },
  ],
  "charcoal": [
    // CHARCOAL
    { name: "Charcoal Chicken Normal", price: "AED 32 / 18", section: "Charcoal" },
    { name: "Charcoal Chicken Peri Peri", price: "AED 34 / 20", section: "Charcoal" },
    { name: "Charcoal Chicken Green Chilli", price: "AED 34 / 20", section: "Charcoal" },
    { name: "Charcoal Pepper Chicken", price: "AED 36 / 20", section: "Charcoal" },
    { name: "Charcoal Mix Chicken", price: "AED 36 / 20", section: "Charcoal" },
  ],
  "curry": [
    // CURRY
    { name: "Aloo Bhaji", price: "AED 3.00", section: "Curry" },
    { name: "Beef Nadan Curry", price: "AED 15.00", section: "Curry" },
    { name: "Cherupayar", price: "AED 3.00", section: "Curry" },
    { name: "Dal Curry", price: "AED 8.00", section: "Curry" },
    { name: "Egg Curry Night", price: "AED 5.00", section: "Curry" },
    { name: "Egg Masala", price: "AED 3.00", section: "Curry" },
    { name: "Egg Roast Night", price: "AED 6.00", section: "Curry" },
    { name: "Mix Veg Large", price: "AED 10.00", section: "Curry" },
    { name: "Mix Veg Small", price: "AED 5.00", section: "Curry" },
    { name: "Veg Kurma", price: "AED 6.00", section: "Curry" },
  ],
  "north-indian": [
    // NORTH INDIAN
    { name: "Aloo Gobi", price: "AED 10.00", section: "North Indian" },
    { name: "Aloo Palak", price: "AED 6.00", section: "North Indian" },
    { name: "Bindi Masala", price: "AED 8.00", section: "North Indian" },
    { name: "Chena Masala", price: "AED 8.00", section: "North Indian" },
    { name: "Chi. Hyderabadi Curry", price: "AED 14.00", section: "North Indian" },
    { name: "Chicken Kabab", price: "AED 8.00", section: "North Indian" },
    { name: "Chicken Kadai", price: "AED 16.00", section: "North Indian" },
    { name: "Chicken Lababder", price: "AED 16.00", section: "North Indian" },
    { name: "Chicken Masala", price: "AED 12.00", section: "North Indian" },
    { name: "Curd Rice", price: "AED 8.00", section: "North Indian" },
    { name: "Dal Fry", price: "AED 10.00", section: "North Indian" },
    { name: "Dal Kichadi", price: "AED 10.00", section: "North Indian" },
    { name: "Dal Tadka", price: "AED 11.00", section: "North Indian" },
    { name: "Green Pease Masala", price: "AED 10.00", section: "North Indian" },
  ],
  "veg-rice": [
    // VEG & RICE
    { name: "Jeera Rice", price: "AED 8.00", section: "Veg & Rice" },
    { name: "Lemon Rice", price: "AED 8.00", section: "Veg & Rice" },
    { name: "Mushroom Masala", price: "AED 11.00", section: "Veg & Rice" },
    { name: "Mutter Mushroom", price: "AED 11.00", section: "Veg & Rice" },
    { name: "Mutter Paneer Masala", price: "AED 12.00", section: "Veg & Rice" },
    { name: "Palak Chicken", price: "AED 16.00", section: "Veg & Rice" },
    { name: "Palak Paneer", price: "AED 12.00", section: "Veg & Rice" },
    { name: "Paneer Butter Masala", price: "AED 12.00", section: "Veg & Rice" },
    { name: "Paneer Kadai", price: "AED 12.00", section: "Veg & Rice" },
    { name: "Veg Kadai", price: "AED 12.00", section: "Veg & Rice" },
    { name: "Veg Pulav", price: "AED 10.00", section: "Veg & Rice" },
    { name: "Tomato Rice", price: "AED 8.00", section: "Veg & Rice" },
    { name: "Paneer Lababdar", price: "AED 12.00", section: "Veg & Rice" },
  ],
  "chinese": [
    // CHINESE
    { name: "Chicken Lollipop", price: "AED 10.00", section: "Chinese" },
    { name: "Chicken 65", price: "AED 12.00", section: "Chinese" },
    { name: "Chicken Fried Rice", price: "AED 12.00", section: "Chinese" },
    { name: "Chicken Manchurian", price: "AED 14.00", section: "Chinese" },
    { name: "Chicken Noodles", price: "AED 12.00", section: "Chinese" },
    { name: "Chicken Schezwan Noodles", price: "AED 13.00", section: "Chinese" },
    { name: "Chilli Chicken", price: "AED 14.00", section: "Chinese" },
    { name: "Chilly Chicken", price: "AED 14.00", section: "Chinese" },
    { name: "Egg Fried Rice", price: "AED 11.00", section: "Chinese" },
    { name: "Egg Noodles", price: "AED 11.00", section: "Chinese" },
    { name: "Extra Noodles", price: "AED 4.00", section: "Chinese" },
    { name: "Gobi Manchurian", price: "AED 11.00", section: "Chinese" },
    { name: "Mix Noodles", price: "AED 18.00", section: "Chinese" },
    { name: "Paneer Chilli", price: "AED 12.00", section: "Chinese" },
    { name: "Schezwan Fried Rice Chicken", price: "AED 13.00", section: "Chinese" },
    { name: "Shezwan Fried Rice Egg", price: "AED 12.00", section: "Chinese" },
    { name: "Shezwan Fried Rice Veg", price: "AED 11.00", section: "Chinese" },
    { name: "Triple Fried Rice", price: "AED 18.00", section: "Chinese" },
    { name: "Veg Fried Rice", price: "AED 10.00", section: "Chinese" },
    { name: "Veg Manchurian", price: "AED 11.00", section: "Chinese" },
    { name: "Veg Noodles", price: "AED 10.00", section: "Chinese" },
  ],
  "burger": [
    // BURGER
    { name: "Beef Burger", price: "AED 10.00", section: "Burger" },
    { name: "Chicken Burger", price: "AED 8.00", section: "Burger" },
    { name: "French Fries", price: "AED 5.00", section: "Burger" },
    { name: "Zinger Burger", price: "AED 12.00", section: "Burger" },
    { name: "Veg Burger", price: "AED 8.00", section: "Burger" },
    { name: "Double Chicken Burger", price: "AED 13.00", section: "Burger" },
    { name: "Double Beef Burger", price: "AED 16.00", section: "Burger" },
  ],
  "sandwich": [
    // SANDWICH
    { name: "Cheese Sandwich", price: "AED 3.00", section: "Sandwiches" },
    { name: "Chicken Sandwich", price: "AED 6.00", section: "Sandwiches" },
    { name: "Club Sandwich", price: "AED 12.00", section: "Sandwiches" },
    { name: "Egg Sandwich", price: "AED 5.00", section: "Sandwiches" },
    { name: "Veg Sandwich", price: "AED 4.00", section: "Sandwiches" },
    { name: "Zinger Sandwich", price: "AED 8.00", section: "Sandwiches" },
  ],
  "egg-items": [
    // EGG ITEMS
    { name: "Double Omelette", price: "AED 4.00", section: "Eggs" },
    { name: "Egg Bhurji", price: "AED 6.00", section: "Eggs" },
    { name: "Single Omelette", price: "AED 2.00", section: "Eggs" },
  ],
  "fish-items": [
    // FISH ITEMS
    { name: "Ayala Fry", price: "APS", section: "Fish" },
    { name: "Fish Fry", price: "APS", section: "Fish" },
    { name: "Fish Masala", price: "APS", section: "Fish" },
    { name: "Fish Nadan Curry", price: "APS", section: "Fish" },
  ],
  "lunch": [
    // LUNCH
    { name: "Biriyani - Veg/Egg/Chicken", price: "AED 8/8/10", section: "Lunch" },
    { name: "Ghee Rice", price: "AED 6.00", section: "Lunch" },
    { name: "Kerala Meals", price: "AED 8.00", section: "Lunch" },
    { name: "Plain Rice", price: "AED 3.00", section: "Lunch" },
    { name: "Pothi Biriyani Chicken/Beef", price: "AED 14/16", section: "Lunch" },
    { name: "Pothi Choru", price: "AED 12.00", section: "Lunch" },
  ],
  "soup": [
    // SOUP
    { name: "Chicken Soup", price: "AED 10.00", section: "Soups" },
    { name: "Veg Hot & Sour Soup", price: "AED 8.00", section: "Soups" },
    { name: "Chicken Manchow Soup", price: "AED 10.00", section: "Soups" },
    { name: "Veg Soup", price: "AED 8.00", section: "Soups" },
    { name: "Veg Manchow Soup", price: "AED 8.00", section: "Soups" },
    { name: "Chicken Hot & Sour Soup", price: "AED 10.00", section: "Soups" },
  ],
  "fresh-juices": [
    // FRESH JUICES
    { name: "Apple Juice", price: "AED 8/10/12", section: "Juices" },
    { name: "Avocado Juice", price: "AED 8/10/12", section: "Juices" },
    { name: "Lemon Juice", price: "AED 5.00", section: "Juices" },
    { name: "Lemon Mint Juice", price: "AED 5.00", section: "Juices" },
    { name: "Mango Juice", price: "AED 8/10/12", section: "Juices" },
    { name: "Orange Juice", price: "AED 10/12", section: "Juices" },
    { name: "Pineapple Juice", price: "AED 8/10/12", section: "Juices" },
    { name: "Fresh Lime Soda", price: "AED 6.00", section: "Juices" },
    { name: "Lemon Soda Mix", price: "AED 7.00", section: "Juices" },
    { name: "Lemon Soda Salt", price: "AED 7.00", section: "Juices" },
    { name: "Lemon Soda Sweet", price: "AED 7.00", section: "Juices" },
  ],
  "mix-juice": [
    // MIX JUICE
    { name: "Avocado + Mango Juice", price: "AED 10.00", section: "Mix Juice" },
    { name: "Orange + Pineapple Juice", price: "AED 12.00", section: "Mix Juice" },
  ],
  "soft-drinks": [
    // SOFT DRINKS
    { name: "Club Soda Can 300 Ml", price: "AED 1.50", section: "Soft Drinks" },
    { name: "Coca Cola 355 Ml", price: "AED 4.00", section: "Soft Drinks" },
    { name: "Dew Can 330 Ml", price: "AED 4.00", section: "Soft Drinks" },
    { name: "Fanta Can 320 Ml", price: "AED 4.00", section: "Soft Drinks" },
    { name: "Pepsi Can 320 Ml", price: "AED 4.00", section: "Soft Drinks" },
    { name: "Soda", price: "AED 1.50", section: "Soft Drinks" },
    { name: "Sprite Can 330 Ml", price: "AED 4.00", section: "Soft Drinks" },
    { name: "Water Big", price: "AED 2.50", section: "Soft Drinks" },
    { name: "Water Small", price: "AED 1.50", section: "Soft Drinks" },
  ],
};
